export const MODULES = [
  'moderation',
  'tickets',
  'onboarding',
  'roles',
  'analytics',
  'profiles',
  'skills',
  'achievements',
  'reputation',
  'mentoring',
  'pairing',
  'projects',
  'bounties',
  'reviews',
  'snippets',
  'battles',
  'code_jams',
  'hackathons',
  'ideas',
  'bug_hunt',
  'rubber_duck',
  'rfc',
  'standups',
  'dev_logs',
  'knowledge',
  'github',
  'releases',
  'uptime',
  'reminders',
  'events',
  'giveaways',
  'polls',
  'suggestions',
  'starboard',
  'voice',
  'threads',
  'digest',
  'streaks',
  'leaderboards',
  'credits',
  'shop',
  'permissions',
  'notifications',
  'audit',
  'diagnostics',
  'developer_tools',
  'bookmarks',
  'todo',
  'focus',
  'missions',
  'dashboard',
] as const;

export type ModuleName = (typeof MODULES)[number];

const COMMAND_MODULE: Record<string, ModuleName> = {
  mod: 'moderation',
  ban: 'moderation',
  kick: 'moderation',
  timeout: 'moderation',
  warn: 'moderation',
  purge: 'moderation',
  slowmode: 'moderation',
  lock: 'moderation',
  unlock: 'moderation',
  nick: 'moderation',
  appeal: 'moderation',
  security: 'moderation',
  ticket: 'tickets',
  onboarding: 'onboarding',
  rolemenu: 'roles',
  analytics: 'analytics',
  insights: 'analytics',
  profile: 'profiles',
  passport: 'profiles',
  skills: 'skills',
  achievements: 'achievements',
  rep: 'reputation',
  mentor: 'mentoring',
  pair: 'pairing',
  project: 'projects',
  discover: 'projects',
  projecthealth: 'projects',
  workspace: 'projects',
  bounty: 'bounties',
  review: 'reviews',
  snippet: 'snippets',
  battle: 'battles',
  codejam: 'code_jams',
  hackathon: 'hackathons',
  idea: 'ideas',
  bughunt: 'bug_hunt',
  rubberduck: 'rubber_duck',
  rfc: 'rfc',
  standup: 'standups',
  standups: 'standups',
  devlog: 'dev_logs',
  docs: 'knowledge',
  github: 'github',
  release: 'releases',
  uptime: 'uptime',
  remind: 'reminders',
  event: 'events',
  giveaway: 'giveaways',
  poll: 'polls',
  suggest: 'suggestions',
  starboard: 'starboard',
  voice: 'voice',
  autothread: 'threads',
  digest: 'digest',
  streak: 'streaks',
  leaderboard: 'leaderboards',
  credits: 'credits',
  shop: 'shop',
  permissions: 'permissions',
  notifications: 'notifications',
  audit: 'audit',
  health: 'diagnostics',
  botstats: 'diagnostics',
  whois: 'diagnostics',
  tools: 'developer_tools',
  playground: 'developer_tools',
  bookmarks: 'bookmarks',
  todo: 'todo',
  focus: 'focus',
  missions: 'missions',
  dashboard: 'dashboard',
};

export function moduleForCommand(command: string): ModuleName | undefined {
  return COMMAND_MODULE[command];
}
